server:
  contextPath: /

spring:
  application:
    name: auction
  datasource:
    url: jdbc:h2:mem:auctiondb_test;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: my_password
    hikari:
      pool-name: H2PoolTest
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false
      path: /h2-console

logging:
  level:
    org:
      springframework:
        security: DEBUG
