server:
  port: 8088
  contextPath: /

spring:
  application:
    name: auction
  datasource:
    url: jdbc:h2:mem:auctiondb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: my_password
    hikari:
      pool-name: H2Pool
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


springdoc:
  packagesToScan: com.auction
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /openapi
  swagger-ui:
    syntax-highlight:
      activated: true
    enabled: true
    url: /openapi
    path: /openapi.html
    operationsSorter: method
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: true
  group-configs:
  default-produces-media-type: application/json
  cache:
    disabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG