### Register with Missing Password
POST http://localhost:8088/v1/api/users
Content-Type: application/json
Authorization: Basic am9obl9kb2U6cGFzc3dvcmQxMjM=

{
  "username": "jack_dorsey",
  "email": "jack_dorsey@auction.com",
  "fullName": "Jack Dorsey",
  "roles": ["user"]
}
